### ISSUE TITLE
[ bug ] Abnormal fingerprint key behavior ( Redmi K30 )

### ISSUE THREAD

**Issue by VergeDX** [crdroidandroid/android_device_xiaomi_phoenix#2]
Hi, I found a bug.  When I touching (not press) the fingerprint key, it will tap the first element of the screen, just like I tap that.  

My device is Redmi K30, maybe the problem is because the model of POCO X2 fingerprint module is not the same as Redmi K30's.  

I also take the logcat, when I do nothing, the log below will be output over and over again:  
`````
04-23 20:58:27.770  1337  1372 W ServiceManagement: Waited one second for vendor.qti.hardware.cacert@1.0::IService/default
04-23 20:58:27.771  1337  1372 I ServiceManagement: getService: Trying again for vendor.qti.hardware.cacert@1.0::IService/default...
04-23 20:58:27.773   538 11245 W libc    : Unable to set property "ctl.interface_start" to "vendor.qti.hardware.cacert@1.0::IService/default": error code: 0x20
04-23 20:58:27.774   538 11245 E hwservicemanager: Failed to set property for starting vendor.qti.hardware.cacert@1.0::IService/default
`````
When I touched the fingerprint key once. it said that:
`````
04-23 20:58:25.864  1352  1548 D fpc_tac : fpc_irq_wait: poll status: 1, revents [0]: 10, [1]: 0
04-23 20:58:25.881  1352  1548 D fpc_fingerprint_hal: report_input_event - Reporting event type: 1, code: 304, value:1
04-23 20:58:25.986  1352  1548 D fpc_tac : fpc_irq_wait: poll status: 1, revents [0]: 10, [1]: 0
04-23 20:58:26.004  1352  1548 D fpc_fingerprint_hal: report_input_event - Reporting event type: 1, code: 304, value:0
04-23 20:58:26.005  1352  1548 D fpc_fingerprint_hal: nav_loop waiting for finger down
`````

@neobuddy89

**Comment by neobuddy89** [comment]
vendor.qti.hardware.cacert@1.0::IService/default
spam cannot be removed until we build vendor ourselves - which is what we are working on.
this spam also exist on Poco X2.

About fingerprint - will look into it further once vendor build is enabled.

**Comment by VergeDX** [comment]
Nice work! Looking forward to subsequent updates.

**Comment by neobuddy89** [comment]
@VergeDX Please test new build and let know

**Comment by VergeDX** [comment]
I cannot use my fingerprint sensor after update to 0428 version...  
There is no option of fingerprint in settings...  
And also, I did not see any logcat about the fingerprint sensor...
@neobuddy89

**Comment by neobuddy89** [comment]
@VergeDX Please restart device, capture logs and share. 
Selinux is now fully enforcing, might be blocking something.

**Comment by VergeDX** [comment]
I run the command `adb wait-for-device shell logcat > logcat` to collect log, here is the full log.  
[logcat.txt](https://github.com/crdroidandroid/android_device_xiaomi_phoenix/files/4549034/logcat.txt)  

I try to search the keyword "fingerprint" and found lots of useful information.  
That is, if any information needed, please let me know : )
@neobuddy89
